package lesson04.part03.task46;
//@FoLoKe
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

import static org.junit.Assert.*;

@RunWith(JUnit4.class)
public class Task46Test {
    /* 1.	Метод main должен вызывать метод method1.
     * 2.	Метод main должен перехватывать исключение Exception1.
     * 3.	Метод main должен перехватывать исключение Exception2.
     * 4.	Метод main должен перехватывать исключение Exception3.
     * 5.	Метод method1 не изменять.
     */

    @Test
    public void test46main() {

    }

    @Test
    public void test4601() {

    }

    @Test
    public void test4602() {

    }

    @Test
    public void test4603() {

    }

    @Test
    public void test4604() {

    }
}